# Generated by Django 3.1.3 on 2021-01-18 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Build',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buildid', models.IntegerField()),
                ('url', models.CharField(max_length=100)),
                ('targetname', models.CharField(max_length=20)),
                ('revision', models.CharField(blank=True, max_length=50, null=True)),
                ('started', models.DateTimeField(verbose_name='Build started')),
                ('completed', models.DateTimeField(blank=True, null=True, verbose_name='Build completed')),
                ('workername', models.CharField(max_length=20)),
                ('status', models.IntegerField(blank=True, choices=[(0, 'Success'), (1, 'Warnings'), (2, 'Failure'), (3, 'Skipped'), (4, 'Exception'), (5, 'Retry'), (6, 'Cancelled')], null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BuildCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buildid', models.IntegerField(unique=True)),
                ('targetname', models.CharField(max_length=20)),
                ('reason', models.CharField(blank=True, max_length=250, null=True)),
                ('owner', models.CharField(blank=True, max_length=250, null=True)),
                ('status', models.IntegerField(blank=True, choices=[(0, 'Success'), (1, 'Warnings'), (2, 'Failure'), (3, 'Skipped'), (4, 'Exception'), (5, 'Retry'), (6, 'Cancelled')], null=True)),
                ('triagenotes', models.CharField(blank=True, max_length=250, null=True)),
                ('forswat', models.BooleanField(default=False)),
                ('branch', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'permissions': [('rest', 'Can use rest API')],
            },
        ),
        migrations.CreateModel(
            name='StepFailure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('triage', models.IntegerField(blank=True, choices=[(0, 'Pending'), (1, 'Mailsent'), (2, 'Bugopened'), (3, 'Otherdone')], null=True)),
                ('status', models.IntegerField(blank=True, choices=[(0, 'Success'), (1, 'Warnings'), (2, 'Failure'), (3, 'Skipped'), (4, 'Exception'), (5, 'Retry'), (6, 'Cancelled')], null=True)),
                ('stepname', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=150)),
                ('build', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='swatapp.build')),
            ],
        ),
        migrations.AddField(
            model_name='build',
            name='buildcollection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='swatapp.buildcollection'),
        ),
    ]
